server:
  port: 8083

spring:
  application:
    name: modulo3

  cloud:
    function:
      definition: lambdaConsumer

    stream:
      bindings:
        lambdaConsumer-in-0:
          destination: pessoa.atualizada
          group: pessoa-group
          content-type: application/json

      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9093}
          auto-create-topics: true

        bindings:
          lambdaConsumer-in-0:
            consumer:
              auto-offset-reset: earliest
              enableDlq: true
